"""initial schema

Revision ID: aa79e19bf109
Revises: 
Create Date: 2026-09-21 12:51:52.225577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa79e19bf109'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emails',
    sa.Column('email_id', sa.String(), nullable=False),
    sa.Column('thread_id', sa.String(), nullable=False),
    sa.Column('sender', sa.String(), nullable=True),
    sa.Column('sender_email', sa.String(), nullable=True),
    sa.Column('recipient', sa.String(), nullable=True),
    sa.Column('cc', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('email_date', sa.DateTime(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('processed_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('email_id')
    )
    op.create_index(op.f('ix_emails_sender_email'), 'emails', ['sender_email'], unique=False)
    op.create_index(op.f('ix_emails_thread_id'), 'emails', ['thread_id'], unique=False)
    op.create_table('oauth_tokens',
    sa.Column('token_id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('mailbox_email', sa.String(), nullable=False),
    sa.Column('encrypted_refresh_token', sa.Text(), nullable=False),
    sa.Column('encrypted_access_token', sa.Text(), nullable=True),
    sa.Column('token_expiry', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('token_id')
    )
    op.create_index(op.f('ix_oauth_tokens_mailbox_email'), 'oauth_tokens', ['mailbox_email'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'FINANCE', 'PROCUREMENT', 'VIEWER', name='userrole', native_enum=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('vendors',
    sa.Column('vendor_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('normalized_name', sa.String(), nullable=False),
    sa.Column('gstin', sa.String(), nullable=True),
    sa.Column('pan', sa.String(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('vendor_id')
    )
    op.create_index(op.f('ix_vendors_gstin'), 'vendors', ['gstin'], unique=False)
    op.create_index(op.f('ix_vendors_name'), 'vendors', ['name'], unique=False)
    op.create_index(op.f('ix_vendors_normalized_name'), 'vendors', ['normalized_name'], unique=False)
    op.create_table('audit_log',
    sa.Column('log_id', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('field', sa.String(), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_audit_log_entity_id'), 'audit_log', ['entity_id'], unique=False)
    op.create_table('documents',
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('email_id', sa.String(), nullable=False),
    sa.Column('attachment_name', sa.String(), nullable=False),
    sa.Column('attachment_size', sa.Integer(), nullable=True),
    sa.Column('document_type', sa.Enum('PURCHASE_ORDER', 'PO_AMENDMENT', 'ORDER_CONFIRMATION', 'GRN', 'GOODS_RECEIPT', 'DELIVERY_CHALLAN', 'TAX_INVOICE', 'DEBIT_NOTE', 'CREDIT_NOTE', 'PROFORMA_INVOICE', 'CANCELLED_DOCUMENT', 'OTHER', name='documenttype', native_enum=False), nullable=True),
    sa.Column('document_number', sa.String(), nullable=True),
    sa.Column('document_date', sa.Date(), nullable=True),
    sa.Column('vendor', sa.String(), nullable=True),
    sa.Column('file_hash', sa.String(), nullable=False),
    sa.Column('file_location', sa.String(), nullable=False),
    sa.Column('extraction_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('classification_reasons', sa.JSON(), nullable=True),
    sa.Column('processing_status', sa.Enum('RECEIVED', 'PARSING', 'CLASSIFIED', 'EXTRACTED', 'VALIDATED', 'APPLIED', 'EXCEPTION', 'DUPLICATE', 'FAILED', name='processingstatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['emails.email_id'], ),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_index(op.f('ix_documents_document_number'), 'documents', ['document_number'], unique=False)
    op.create_index(op.f('ix_documents_email_id'), 'documents', ['email_id'], unique=False)
    op.create_index(op.f('ix_documents_file_hash'), 'documents', ['file_hash'], unique=False)
    op.create_table('extraction_audit',
    sa.Column('audit_id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('raw_response', sa.JSON(), nullable=True),
    sa.Column('field_confidence', sa.JSON(), nullable=True),
    sa.Column('overall_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_index(op.f('ix_extraction_audit_document_id'), 'extraction_audit', ['document_id'], unique=False)
    op.create_table('po_master',
    sa.Column('po_id', sa.String(), nullable=False),
    sa.Column('po_number', sa.String(), nullable=False),
    sa.Column('po_date', sa.Date(), nullable=True),
    sa.Column('vendor_id', sa.String(), nullable=True),
    sa.Column('vendor_name', sa.String(), nullable=True),
    sa.Column('vendor_gstin', sa.String(), nullable=True),
    sa.Column('vendor_pan', sa.String(), nullable=True),
    sa.Column('vendor_address', sa.Text(), nullable=True),
    sa.Column('buyer_entity', sa.String(), nullable=True),
    sa.Column('buyer_gstin', sa.String(), nullable=True),
    sa.Column('ship_to', sa.Text(), nullable=True),
    sa.Column('bill_to', sa.Text(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('payment_terms', sa.String(), nullable=True),
    sa.Column('delivery_terms', sa.String(), nullable=True),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.Column('po_validity', sa.Date(), nullable=True),
    sa.Column('buyer_reference', sa.String(), nullable=True),
    sa.Column('vendor_reference', sa.String(), nullable=True),
    sa.Column('gross_po_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('taxable_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cgst', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('sgst', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('igst', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('other_taxes', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('freight', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('discount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('other_charges', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('tax_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_po_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('status', sa.Enum('PO_RECEIVED', 'PO_CONFIRMED', 'PENDING_DELIVERY', 'PARTIALLY_RECEIVED', 'FULLY_RECEIVED', 'PARTIALLY_INVOICED', 'FULLY_INVOICED', 'CLOSED', 'OVERDUE', 'CANCELLED', 'EXCEPTION', 'DUPLICATE', name='postatus', native_enum=False), nullable=False),
    sa.Column('source_document_id', sa.String(), nullable=True),
    sa.Column('source_email_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.document_id'], ),
    sa.ForeignKeyConstraint(['source_email_id'], ['emails.email_id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.vendor_id'], ),
    sa.PrimaryKeyConstraint('po_id')
    )
    op.create_index(op.f('ix_po_master_po_number'), 'po_master', ['po_number'], unique=False)
    op.create_table('exceptions',
    sa.Column('exception_id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=True),
    sa.Column('po_id', sa.String(), nullable=True),
    sa.Column('exception_type', sa.Enum('PO_NUMBER_MISSING', 'DUPLICATE_PO', 'DUPLICATE_ATTACHMENT', 'GST_MISMATCH', 'VENDOR_MISMATCH', 'PO_TOTAL_MISMATCH', 'UNREADABLE_ATTACHMENT', 'UNSUPPORTED_DOCUMENT', 'LOW_CLASSIFICATION_CONFIDENCE', 'LOW_FIELD_CONFIDENCE', 'GRN_CANNOT_BE_MATCHED', 'INVOICE_CANNOT_BE_MATCHED', 'NOTE_CANNOT_BE_MATCHED', 'MULTIPLE_POSSIBLE_PO_MATCH', 'QUANTITY_EXCEEDS_PO_QUANTITY', 'INVOICE_EXCEEDS_PO_VALUE', 'GRN_EXCEEDS_PO_QUANTITY', 'MISSING_EXPECTED_DELIVERY_DATE', 'NEGATIVE_OR_ZERO_QUANTITY', 'ABNORMAL_TAX_RATE', 'INVALID_GSTIN_FORMAT', 'MISSING_TOTAL', name='exceptiontype', native_enum=False), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='exceptionseverity', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_REVIEW', 'APPROVED', 'REJECTED', 'RESOLVED', name='exceptionstatus', native_enum=False), nullable=False),
    sa.Column('candidate_data', sa.JSON(), nullable=True),
    sa.Column('assigned_to', sa.String(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('resolved_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ),
    sa.ForeignKeyConstraint(['po_id'], ['po_master.po_id'], ),
    sa.PrimaryKeyConstraint('exception_id')
    )
    op.create_index(op.f('ix_exceptions_document_id'), 'exceptions', ['document_id'], unique=False)
    op.create_table('grn',
    sa.Column('grn_id', sa.String(), nullable=False),
    sa.Column('grn_number', sa.String(), nullable=True),
    sa.Column('grn_date', sa.Date(), nullable=True),
    sa.Column('po_id', sa.String(), nullable=True),
    sa.Column('vendor', sa.String(), nullable=True),
    sa.Column('received_quantity', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('received_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('warehouse_location', sa.String(), nullable=True),
    sa.Column('source_document_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['po_id'], ['po_master.po_id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.document_id'], ),
    sa.PrimaryKeyConstraint('grn_id')
    )
    op.create_index(op.f('ix_grn_grn_number'), 'grn', ['grn_number'], unique=False)
    op.create_index(op.f('ix_grn_po_id'), 'grn', ['po_id'], unique=False)
    op.create_table('po_lines',
    sa.Column('po_line_id', sa.String(), nullable=False),
    sa.Column('po_id', sa.String(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('item_code', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('hsn', sa.String(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('uom', sa.String(), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('discount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('tax_rate', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('line_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('expected_delivery_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['po_id'], ['po_master.po_id'], ),
    sa.PrimaryKeyConstraint('po_line_id')
    )
    op.create_index(op.f('ix_po_lines_po_id'), 'po_lines', ['po_id'], unique=False)
    op.create_table('grn_lines',
    sa.Column('grn_line_id', sa.String(), nullable=False),
    sa.Column('grn_id', sa.String(), nullable=False),
    sa.Column('po_line_id', sa.String(), nullable=True),
    sa.Column('item_code', sa.String(), nullable=True),
    sa.Column('received_quantity', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('accepted_quantity', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('rejected_quantity', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['grn_id'], ['grn.grn_id'], ),
    sa.ForeignKeyConstraint(['po_line_id'], ['po_lines.po_line_id'], ),
    sa.PrimaryKeyConstraint('grn_line_id')
    )
    op.create_index(op.f('ix_grn_lines_grn_id'), 'grn_lines', ['grn_id'], unique=False)
    op.create_index(op.f('ix_grn_lines_po_line_id'), 'grn_lines', ['po_line_id'], unique=False)
    op.create_table('invoices',
    sa.Column('invoice_id', sa.String(), nullable=False),
    sa.Column('invoice_number', sa.String(), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('po_id', sa.String(), nullable=True),
    sa.Column('grn_id', sa.String(), nullable=True),
    sa.Column('taxable_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('gst', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('source_document_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['grn_id'], ['grn.grn_id'], ),
    sa.ForeignKeyConstraint(['po_id'], ['po_master.po_id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.document_id'], ),
    sa.PrimaryKeyConstraint('invoice_id')
    )
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=False)
    op.create_index(op.f('ix_invoices_po_id'), 'invoices', ['po_id'], unique=False)
    op.create_table('debit_credit_notes',
    sa.Column('note_id', sa.String(), nullable=False),
    sa.Column('note_type', sa.Enum('DEBIT_NOTE', 'CREDIT_NOTE', name='notetype', native_enum=False), nullable=False),
    sa.Column('note_number', sa.String(), nullable=True),
    sa.Column('note_date', sa.Date(), nullable=True),
    sa.Column('po_id', sa.String(), nullable=True),
    sa.Column('invoice_id', sa.String(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('taxable_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('gst', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('source_document_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.invoice_id'], ),
    sa.ForeignKeyConstraint(['po_id'], ['po_master.po_id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.document_id'], ),
    sa.PrimaryKeyConstraint('note_id')
    )
    op.create_index(op.f('ix_debit_credit_notes_note_number'), 'debit_credit_notes', ['note_number'], unique=False)
    op.create_index(op.f('ix_debit_credit_notes_po_id'), 'debit_credit_notes', ['po_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_debit_credit_notes_po_id'), table_name='debit_credit_notes')
    op.drop_index(op.f('ix_debit_credit_notes_note_number'), table_name='debit_credit_notes')
    op.drop_table('debit_credit_notes')
    op.drop_index(op.f('ix_invoices_po_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_grn_lines_po_line_id'), table_name='grn_lines')
    op.drop_index(op.f('ix_grn_lines_grn_id'), table_name='grn_lines')
    op.drop_table('grn_lines')
    op.drop_index(op.f('ix_po_lines_po_id'), table_name='po_lines')
    op.drop_table('po_lines')
    op.drop_index(op.f('ix_grn_po_id'), table_name='grn')
    op.drop_index(op.f('ix_grn_grn_number'), table_name='grn')
    op.drop_table('grn')
    op.drop_index(op.f('ix_exceptions_document_id'), table_name='exceptions')
    op.drop_table('exceptions')
    op.drop_index(op.f('ix_po_master_po_number'), table_name='po_master')
    op.drop_table('po_master')
    op.drop_index(op.f('ix_extraction_audit_document_id'), table_name='extraction_audit')
    op.drop_table('extraction_audit')
    op.drop_index(op.f('ix_documents_file_hash'), table_name='documents')
    op.drop_index(op.f('ix_documents_email_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_document_number'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_audit_log_entity_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_vendors_normalized_name'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_name'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_gstin'), table_name='vendors')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_oauth_tokens_mailbox_email'), table_name='oauth_tokens')
    op.drop_table('oauth_tokens')
    op.drop_index(op.f('ix_emails_thread_id'), table_name='emails')
    op.drop_index(op.f('ix_emails_sender_email'), table_name='emails')
    op.drop_table('emails')
    # ### end Alembic commands ###
